### PR TITLE
First release of a gem 

### PR DESCRIPTION
**Pull request by rderoldan1**
I just turn in a Gem, can you try it, I added me as a contributor I hope you are agree, I need your email in order to your photo appear in gem description.
http://rubygems.org/gems/usagewatch

### CODE REVIEW

**Comment by rderoldan1** [comment]
Also Ryan have a nice tutorial 
http://railscasts.com/episodes/245-new-gem-with-bundler

**Comment by nethacker** [comment]
My email is nethacker@gmail.com I will test it out, and I don't mind you being a contributor.

**Comment by nethacker** [comment]
Is the gem working for you? Also I don't see it listed among My Gems does this take time? Same with the picture.

**Comment by rderoldan1** [comment]
Now you appear there, I had write your email bad :(

Yes, the gem is working, look at the documentation at my repo https://github.com/rderoldan1/usagewatch

This is my ubuntu server

Ruben Espinosa Roldan
rderoldan1@gmail.com

**Comment by nethacker** [comment]
Ok I am trying to run through the merge since there are conflicts.

**Comment by nethacker** [comment]
OK I think I resolved the conflicts for merge let me know if it looks right to you. Thanks. -Phil

**Comment by nethacker** [comment]
Ok I updated some of the Author, Contributor documentation on the files. Thanks for making my Class into a gem.

I tested the gem works fine.

Cheers!

-Phil

**Pull request merged**
